services:
  # Laravel PHPコンテナ
  php:
    platform: linux/x86_64
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/laravel:/var/www/src/laravel
    networks:
      - app-network
    ports:
      - "8000:8000"

  # nginx（バックエンドのプロキシ）
  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/laravel:/var/www/src/laravel
    networks:
      - app-network
    depends_on:
      - php

  # MySQLデータベース
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

  # phpMyAdmin（開発環境用）
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    networks:
      - app-network

  queue-worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    command: php /var/www/artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./src/laravel:/var/www
    networks:
      - app-network
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

  # Nuxt.js（フロントエンド）
  nuxt:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    command: sh -c "npx nuxi build && nuxt start"
    volumes:
      - ./src/nuxt:/usr/src/app
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - php

networks:
  app-network:
    driver: bridge
